// App/LayoutWithTimeout.tsx
import * as React from "react";
import { getLayoutElement } from "./factories";
import "./LayoutWithTimeout.scss";
import { useTileLastUpdateTimestamp } from "./useTileLastUpdateTimestamp";

export const LayoutWithTimeout: React.FunctionComponent<{
  id: string;
  timeInMs: number;
  title: string;
  layout?: string;
  layoutProps?: any;
  defaultLastTimestamp?: number;
}> = ({ id, timeInMs, defaultLastTimestamp, title, layout, layoutProps, children }) => {
  const [lastUpdate] = useTileLastUpdateTimestamp(id, defaultLastTimestamp || Date.now());
  const [timeoutInstance, setTimeoutInstance] = React.useState<number>();
  const [timeoutReached, setTimeoutReached] = React.useState<boolean>(false);

  const clearTimeout = React.useCallback(() => {
    self.clearTimeout(timeoutInstance);
  }, [timeoutInstance]);

  React.useEffect(() => {
    clearTimeout();
    const timeUntilTimeout = lastUpdate ? Math.max((lastUpdate + timeInMs) - Date.now(), 0) : 0;
    if (timeUntilTimeout === 0) {
      setTimeoutReached(true);
    } else {
      setTimeoutReached(false);
      const instance = self.setTimeout(() => {
        setTimeoutReached(true);
      }, timeUntilTimeout);
      setTimeoutInstance(instance);
    }
  }, [timeInMs, lastUpdate]);

  const Layout = getLayoutElement(layout);

  return (
    <Layout tileId={id} title={title} {...layoutProps}>
      {timeoutReached && (
        <div className="timeout-overlay">
          <div>Timeout reached</div>
          <div>⌛</div>
        </div>
      )}
      {children}
    </Layout>
  );
};

// App/LayoutWithTimeout.svelte
<script lang="ts">
  import RectangleTile from "./layout/RectangleTile.svelte";

  export let timeInMs: number;
  export let title: string = "";
  export let layout: string | undefined = undefined;
  export let layoutProps: any;
  export let lastTimestamp: number;

  $: lastTimestamp && resetTimeout();

  let timeoutInstance: any;
  let timeoutReached = false;

  function resetTimeout() {
    const timeUntilTimeout = lastTimestamp
      ? Math.max(lastTimestamp + timeInMs - Date.now(), 0)
      : 0;
    timeoutReached = false;
    clearTimeout(timeoutInstance);
    timeoutInstance = globalThis.setTimeout(() => {
      timeoutReached = true;
    }, timeUntilTimeout);
  }

  const specificLayoutProps: {
    [name: string]: { width?: number; height?: number };
  } = {
    rectangle: {
      width: 2,
    },
    large: {
      width: 2,
      height: 2,
    },
    square: {},
  };
</script>

<RectangleTile
  {title}
  breakLayout={layoutProps?.breakLayout || layoutProps?.break}
  {...layoutProps}
  {...specificLayoutProps[layout?.toLowerCase() || "square"] || {}}
>
  {#if timeoutReached}
    <div class="timeout-overlay">
      <div>Timeout reached</div>
      <div>⌛</div>
    </div>
  {:else}
    <slot />
  {/if}
</RectangleTile>

<style>
  .timeout-overlay {
    display: flex;
    flex: 1;
    text-align: center;
    justify-content: space-evenly;
    font-size: 2em;
    flex-direction: column;
  }
</style>
